### PR TITLE
refactor read_trees

### PR DESCRIPTION
**Pull request by SimonGreenhill**
This PR refactors the read_trees method to add remove_burnin and sample.

Having these methods implemented directly in the read_trees method makes the code cleaner e.g.:

```python
# before:
posterior = self.read_nexus(self.raw_dir / 'trees.gz')
posterior = self.sample(self.remove_burnin(posterior, 1001), 1000)
posterior.trees.detranslate()
args.writer.add_posterior(posterior.trees.trees, self.metadata, args.log)
            
# after:
posterior = self.read_trees(self.raw_dir / 'trees.gz', burnin=1001, sample=1000, detranslate=True)
args.writer.add_posterior(posterior, self.metadata, args.log)
```

It's also possibly safer (e.g. burn-in must always be removed before sampling) and faster (i.e. there are some implicit nexus->string conversions that might not happen, and it's easier for me to not have to remember which methods take nexus objects and which take strings)

There's a number of other refactorings that could also happen here:

1. Move `remove_rate` from [read_nexus](https://github.com/phlorest/phlorest/blob/main/src/phlorest/dataset.py#L22-L40) and implement in `read_trees`. These rate things are only found on trees, so this can live better in read_trees.

2. Remove `Dataset.remove_burnin` and `Dataset.sample` from [here](https://github.com/phlorest/phlorest/blob/df835011e704d52e792ae973bc2e5da9fd6725db/src/phlorest/dataset.py#L134-L151). These are surplus and having them in one place is better. However, removing them makes the pipeline less decomposible (e.g. maybe someone wants to call remove_burnin somewhere else ... but I don't see that as being high likelihood)?

3. I haven't implement the seed handling that's in `Dataset.sample` [here](https://github.com/phlorest/phlorest/blob/df835011e704d52e792ae973bc2e5da9fd6725db/src/phlorest/dataset.py#L140-L145). Is this necessary?

4. do we need the single tree method `read_tree` [here](https://github.com/phlorest/phlorest/blob/df835011e704d52e792ae973bc2e5da9fd6725db/src/phlorest/dataset.py#L52-L58)? it's just a wrapper around `read_trees` that takes the first item. It's so we can:

```python
args.writer.add_summary(self.raw_dir.read_tree('..'), self.metadata, args.log)
# instead of 
args.writer.add_summary(self.raw_dir.read_trees('..')[0], self.metadata, args.log)
```

... but I don't think the second form is too ugly, and should add_summary be able to just take the tree anyway?

What do you think @xrotwang?

### CODE REVIEW

**Comment by xrotwang** [comment]
Re 2.: I thought it would be nice to only have to import one thing (`Dataset`) from `phlorest` - and then have all necessary functionality available as methods. But we already have some inheritance and thus less transparency on what's available from `Dataset`. So, yes, importing this functionality as stand-alone functions from `phlorest` may be more transparent.

**Comment by xrotwang** [comment]
Re 1.: I think the reason rate removal ended up in `read_nexus` was that it needs to happen via regex before anything is passed into either nexus reading or newick reading.

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
@SimonGreenhill I think we should merge this and 1, 2, 3 to separate issues/PRs.

Re 4.: No strong opinion from me. I always liked API like e.g. SQLAlchemy's `.first()` to retrieve a single object from what *looks like* a list - but could also be a generator.

**Comment by SimonGreenhill** [comment]
ok, I'll merge and make issues for the others.

https://github.com/phlorest/phlorest/issues/19, https://github.com/cldf/cldfbench/issues/76

I'll keep the singleton add_tree method as is for now.

**Pull request merged**
